[package]
name = "more-options"
version = "1.0.0"
edition = "2018"
authors = ["Chris Martinez <chris_martinez_77@hotmail.com>"]
description = "Provides support for options"
keywords = ["more", "options"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/commonsensesoftware/more-rs-options"
include = ["src/*.rs", "README.md"]

[lib]
name = "options"
path = "src/lib.rs"
doctest = false

[features]
di = ["more-di"]
cfg = ["di", "more-config", "serde"]
async = ["more-di/async"]

[dependencies]
more-changetoken = "1.0"
more-di = { version = "1.0", optional = true, features = ["builder"] }
serde = { version = "1.0", optional = true }

[dependencies.more-config]
version = "1.0"
default-features = false
features = ["binder"]
optional = true

[dev-dependencies]
more-config = { version = "1.0", features = ["mem", "binder"] }
more-di = { version = "1.0", features = ["builder"] }
more-options = { path = ".", features = ["cfg"] }
serde = { version = "1.0", features = ["derive"] }
test-case = "2.2.1"