[package]
name = "more-options"
version = "1.0.0"
authors = ["Chris Martinez"]
edition = "2018"
publish = false
description = "Provides support for options"
keywords = ["more", "options"]
readme = "README.md"

[lib]
name = "options"
path = "src/lib.rs"
doctest = false

[features]
di = ["more-di"]
cfg = ["di", "more-config", "serde"]
async = ["more-di/async"]

[dependencies]
serde = { version = "1.0", optional = true }

[dependencies.more-changetoken]
# TODO: update after publish to crates.io
git = "https://github.com/commonsensesoftware/more-rs-changetoken"

[dependencies.more-di]
# TODO: update after publish to crates.io
git = "https://github.com/commonsensesoftware/more-rs-di"
features = ["builder"]
optional = true

[dependencies.more-config]
# TODO: update after publish to crates.io
git = "https://github.com/commonsensesoftware/more-rs-config"
default-features = false
features = ["binder"]
optional = true

[dev-dependencies]
test-case = "2.2.1"
more-options = { path = ".", features = ["cfg"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies.more-di]
# TODO: update after publish to crates.io
git = "https://github.com/commonsensesoftware/more-rs-di"
features = ["builder"]

[dev-dependencies.more-config]
# TODO: update after publish to crates.io
git = "https://github.com/commonsensesoftware/more-rs-config"
features = ["mem", "binder"]